### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [azimin/AZTransition#4]
dyld: Library not loaded: @rpath/AZTransitions.framework/AZTransitions
  Referenced from: /var/containers/Bundle/Application/B3087059-617D-4269-85EC-8624CF68B164/iOS Example.app/iOS Example
  Reason: image not found

**Comment by azimin** [comment]
@gerchicov-bp thank you for this issue, fixed in https://github.com/azimin/AZTransitions/pull/5
Now should work on the real device (tested)
